### ISSUE TITLE
请问如何在deploy中切换region？

### ISSUE THREAD

**Issue by mkcczh** [zizifn/v2ray-heroku#10]
在main加入
heroku-deploy
with:
  region: "eu"

deploy出来还是us。

**Comment by zizifn** [comment]
好问题。按照文档应该好用，我有如下，两种尝试，
1. 自己手动创建一个可以eu吗？
2. 如果可以，建议删除项目，只使用action 创建/deploy 项目。
https://github.com/marketplace/actions/deploy-to-heroku
https://devcenter.heroku.com/articles/regions#viewing-available-regions

你可以先尝试，等我下班在试试可不可以

**Comment by mkcczh** [comment]
谢谢，试了下，要手动创建app，eu，然后deploy，我还加了region 做 secrets，不加可能也行，但我没试了。

**Comment by zizifn** [comment]
@mkcczh 我增加了，region的支持。如果你有时间，可以拉去最新code 试试。

**Comment by mkcczh** [comment]
好的，谢谢！
