### ISSUE TITLE
目前因为cloudflare workers没法用了，这个方法应该不行了

### ISSUE THREAD

**Issue by Nicolas-Gong** [zizifn/v2ray-heroku#12]
前不久优选IP开始没法用了，所以导致现在heroku只能直连很慢，查了下好像是cloudflare被薅秃了，开始不给普通用户使用ip了，有新的解决方案，使用cloudflare argo就可以了，得到的域名是trycloudflare.com，所以现在的镜像需要修改内容来支持了。

`https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64`

`./cloudflared-linux-amd64 tunnel --url http://localhost:8888 --no-autoupdate>argo.log 2>&1 &`

**Comment by zizifn** [comment]
让我了解下，什么是argo。你的建议是，移除workers的说明，加入argo?

**Comment by zizifn** [comment]
Argo付费啊？

**Comment by Nicolas-Gong** [comment]
> 让我了解下，什么是argo。你的建议是，移除workers的说明，加入argo?

不是这么简单，需要执行我上面的第二条命令来生成trycloudflare.com的反代域名，生成的域名相当于以前的workers内生成的域名。
第一条命令是需要下载这个文件，第二条命令是执行下载下来的文件，其中8888是v2ray的端口号。
目前这个方案是免费的，而且不需要注册任何账号，可以看做服务器的ip被cf添加了ddns了一样。

**Comment by zizifn** [comment]
> > 让我了解下，什么是argo。你的建议是，移除workers的说明，加入argo?
> 
> 不是这么简单，需要执行我上面的第二条命令来生成trycloudflare.com的反代域名，生成的域名相当于以前的workers内生成的域名。 第一条命令是需要下载这个文件，第二条命令是执行下载下来的文件，其中8888是v2ray的端口号。 目前这个方案是免费的，而且不需要注册任何账号，可以看做服务器的ip被cf添加了ddns了一样。

所以你的意思是，
1. 如果在 heroku 上运行下面的命令，`./cloudflared-linux-amd64 tunnel --url http://localhost:8888 --no-autoupdate>argo.log 2>&1 &`
2. cloudflare 会生成一个trycloudflare.com 的域名，并且绑定到 heroku app上
3. 这样访问trycloudflare.com，就会被cloudflare， route 到heroku app。。

如果是这样，我好奇的是cloudflare怎么知道heroku app的域名或者ip？

**Comment by Nicolas-Gong** [comment]
> 

你应该了解内网穿透吧，原理估计和这个类似吧，只是我不知道如何让用户轻易的知道argo.log内的域名是啥。。。

**Comment by Nicolas-Gong** [comment]
2022-04-03T12:37:34Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2022-04-03T12:37:34Z INF Requesting new quick Tunnel on trycloudflare.com...
2022-04-03T12:37:41Z INF +--------------------------------------------------------------------------------------------+
2022-04-03T12:37:41Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2022-04-03T12:37:41Z INF |  https://xxx-xxx-xxx-xx.trycloudflare.com                                   |
2022-04-03T12:37:41Z INF +--------------------------------------------------------------------------------------------+
2022-04-03T12:37:41Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2022-04-03T12:37:41Z INF Version 2022.3.4
2022-04-03T12:37:41Z INF GOOS: linux, GOVersion: go1.17.5, GoArch: amd64
2022-04-03T12:37:41Z INF Settings: map[no-autoupdate:true protocol:quic url:http://localhost:8888]
2022-04-03T12:37:41Z INF Generated Connector ID: 91ed24faec215ac5
2022-04-03T12:37:41Z INF Initial protocol quic
2022-04-03T12:37:41Z INF Starting metrics server on 127.0.0.1:37675/metrics
2022/04/03 20:37:41 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
2022-04-03T12:37:41Z ERR Failed to serve quic connection error="Unauthorized: Failed to get tunnel" connIndex=0
2022-04-03T12:37:41Z ERR Register tunnel error from server side error="Unauthorized: Failed to get tunnel" connIndex=0
2022-04-03T12:37:42Z INF Retrying connection in up to 2s seconds connIndex=0
2022-04-03T12:37:44Z ERR Failed to serve quic connection error="Unauthorized: Failed to get tunnel" connIndex=0
2022-04-03T12:37:44Z ERR Register tunnel error from server side error="Unauthorized: Failed to get tunnel" connIndex=0
2022-04-03T12:37:44Z INF Retrying connection in up to 4s seconds connIndex=0
2022-04-03T12:37:48Z INF Connection 3cebe47be286 registered connIndex=0 location=SIN
2022-04-03T12:37:49Z INF Connection 1d2d955 registered connIndex=1 location=HKG
2022-04-03T12:37:50Z INF Connection 799d17c9fa44 registered connIndex=2 location=SIN
2022-04-03T12:37:51Z INF Connection be8375dcd9b registered connIndex=3 location=HKG


argo.log的内容是上面这个，链接在方框内。

**Comment by zizifn** [comment]
> tunnel --url http://localhost:8888 --no-autoupdate

ok! 我理解了。。那么这个和 https://***.workers.dev/ 区别是，
1. ***.workers.dev **不能**使用静态IP
2. **.trycloudflare.com **可以**使用静态IP

以上理解对吗？

**Comment by Nicolas-Gong** [comment]
> > tunnel --url http://localhost:8888 --no-autoupdate
> 
> ok! 我理解了。。那么这个和 https://***.workers.dev/ 区别是，
> 
> 1. ***.workers.dev **不能**使用静态IP
> 2. **.trycloudflare.com **可以**使用静态IP
> 
> 以上理解对吗？

wokers.dev应该不开放给普通用户了，需要付费用户了。
trycloudflare.com是目前还免费的反代方案。

**Comment by zizifn** [comment]
> > > tunnel --url http://localhost:8888 --no-autoupdate
> > 
> > 
> > ok! 我理解了。。那么这个和 https://***.workers.dev/ 区别是，
> > 
> > 1. ***.workers.dev **不能**使用静态IP
> > 2. **.trycloudflare.com **可以**使用静态IP
> > 
> > 以上理解对吗？
> 
> wokers.dev应该不开放给普通用户了，需要付费用户了。 trycloudflare.com是目前还免费的反代方案wo g

> > > tunnel --url http://localhost:8888 --no-autoupdate
> > 
> > 
> > ok! 我理解了。。那么这个和 https://***.workers.dev/ 区别是，
> > 
> > 1. ***.workers.dev **不能**使用静态IP
> > 2. **.trycloudflare.com **可以**使用静态IP
> > 
> > 以上理解对吗？
> 
> wokers.dev应该不开放给普通用户了，需要付费用户了。 trycloudflare.com是目前还免费的反代方案。

我的 account wokers.dev 还是可用的，免费。让了解下这个 cloudflared tunnel。。另外我这个项目只是做备用，稳定提供不是目的。而且正如所说，即使可以，拿到 argo.log里面内容，需要用户登录到 herokuapp console

**Comment by Nicolas-Gong** [comment]
> > > > tunnel --url http://localhost:8888 --no-autoupdate
> > > 
> > > 
> > > ok! 我理解了。。那么这个和 https://***.workers.dev/ 区别是，
> > > 
> > > 1. ***.workers.dev **不能**使用静态IP
> > > 2. **.trycloudflare.com **可以**使用静态IP
> > > 
> > > 以上理解对吗？
> > 
> > 
> > wokers.dev应该不开放给普通用户了，需要付费用户了。 trycloudflare.com是目前还免费的反代方案wo g
> 
> > > > tunnel --url http://localhost:8888 --no-autoupdate
> > > 
> > > 
> > > ok! 我理解了。。那么这个和 https://***.workers.dev/ 区别是，
> > > 
> > > 1. ***.workers.dev **不能**使用静态IP
> > > 2. **.trycloudflare.com **可以**使用静态IP
> > > 
> > > 以上理解对吗？
> > 
> > 
> > wokers.dev应该不开放给普通用户了，需要付费用户了。 trycloudflare.com是目前还免费的反代方案。
> 
> 我的 account wokers.dev 还是可用的，免费。让了解下这个 cloudflared tunnel。。另外我这个项目只是做备用，稳定提供不是目的。而且正如所说，即使可以，拿到 argo.log里面内容，需要用户登录到 herokuapp console

是的，获取域名很麻烦。。。

**Comment by zizifn** [comment]
> > > > > tunnel --url http://localhost:8888 --no-autoupdate
> > > > 
> > > > 
> > > > ok! 我理解了。。那么这个和 https://***.workers.dev/ 区别是，
> > > > 
> > > > 1. ***.workers.dev **不能**使用静态IP
> > > > 2. **.trycloudflare.com **可以**使用静态IP
> > > > 
> > > > 以上理解对吗？
> > > 
> > > 
> > > wokers.dev应该不开放给普通用户了，需要付费用户了。 trycloudflare.com是目前还免费的反代方案wo g
> > 
> > 
> > > > > tunnel --url http://localhost:8888 --no-autoupdate
> > > > 
> > > > 
> > > > ok! 我理解了。。那么这个和 https://***.workers.dev/ 区别是，
> > > > 
> > > > 1. ***.workers.dev **不能**使用静态IP
> > > > 2. **.trycloudflare.com **可以**使用静态IP
> > > > 
> > > > 以上理解对吗？
> > > 
> > > 
> > > wokers.dev应该不开放给普通用户了，需要付费用户了。 trycloudflare.com是目前还免费的反代方案。
> > 
> > 
> > 我的 account wokers.dev 还是可用的，免费。让了解下这个 cloudflared tunnel。。另外我这个项目只是做备用，稳定提供不是目的。而且正如所说，即使可以，拿到 argo.log里面内容，需要用户登录到 herokuapp console
> 
> 是的，获取域名很麻烦。。。

我现在最想做的是，需要用户自己申请，zero-trust argo tunnel（免费但是需要绑定信用卡），然后绑定自己sub domain，这样自需要，用户传入argo tunnel的access token。。这样用户可以使用自己域名，通过tunnel 访问herokuapp的app.

这样麻烦，但是稳健。。你什么看法?

**Comment by Nicolas-Gong** [comment]
> > > > > > tunnel --url http://localhost:8888 --no-autoupdate
> > > > > 
> > > > > 
> > > > > ok! 我理解了。。那么这个和 https://***.workers.dev/ 区别是，
> > > > > 
> > > > > 1. ***.workers.dev **不能**使用静态IP
> > > > > 2. **.trycloudflare.com **可以**使用静态IP
> > > > > 
> > > > > 以上理解对吗？
> > > > 
> > > > 
> > > > wokers.dev应该不开放给普通用户了，需要付费用户了。 trycloudflare.com是目前还免费的反代方案wo g
> > > 
> > > 
> > > > > > tunnel --url http://localhost:8888 --no-autoupdate
> > > > > 
> > > > > 
> > > > > ok! 我理解了。。那么这个和 https://***.workers.dev/ 区别是，
> > > > > 
> > > > > 1. ***.workers.dev **不能**使用静态IP
> > > > > 2. **.trycloudflare.com **可以**使用静态IP
> > > > > 
> > > > > 以上理解对吗？
> > > > 
> > > > 
> > > > wokers.dev应该不开放给普通用户了，需要付费用户了。 trycloudflare.com是目前还免费的反代方案。
> > > 
> > > 
> > > 我的 account wokers.dev 还是可用的，免费。让了解下这个 cloudflared tunnel。。另外我这个项目只是做备用，稳定提供不是目的。而且正如所说，即使可以，拿到 argo.log里面内容，需要用户登录到 herokuapp console
> > 
> > 
> > 是的，获取域名很麻烦。。。
> 
> 我现在最想做的是，需要用户自己申请，zero-trust argo tunnel（免费但是需要绑定信用卡），然后绑定自己sub domain，这样自需要，用户传入argo tunnel的access token。。这样用户可以使用自己域名，通过tunnel 访问herokuapp的app.
> 
> 这样麻烦，但是稳健。。你什么看法?

可以，可能有些人没有visa，有一定门槛了，不过过滤了部分人也好，羊毛薅的没那么快，死的也慢点。

**Comment by Nicolas-Gong** [comment]
试了下你新搞的分支，速度起来了，不过需要注意的是在配置网络的时候要在header里的host加上heroku给的域名，这个坑我找了很久。

**Comment by zizifn** [comment]
> 试了下你新搞的分支，速度起来了，不过需要注意的是在配置网络的时候要在header里的host加上heroku给的域名，这个坑我找了很久。

貌似我在 readme，tunnel章节，有提到这一点，这个也坑了我好久。。如果可以，一会我回家merge pr。。

**Comment by zizifn** [comment]
> 试了下你新搞的分支，速度起来了，不过需要注意的是在配置网络的时候要在header里的host加上heroku给的域名，这个坑我找了很久。

另外，谢谢告知tunnel这个功能，体验了下，蛮有意思的。甚至可以免费白嫖，他们warp client VPN 服务。

**Comment by zizifn** [comment]
@Nicolas-Gong  我最近发现，如果长时间不用heroku app & tunnel 不会从休眠回来，会挂掉，需要重新部署。。不知道你遇到过吗？

**Comment by Nicolas-Gong** [comment]
> @Nicolas-Gong 我最近发现，如果长时间不用heroku app & tunnel 不会从休眠回来，会挂掉，需要重新部署。。不知道你遇到过吗？

第一天我就遇到这个问题了，我以为你自己解决了。。。其实很简单我是放在路由，每隔29分钟访问一次heroku给的链接
*/29 * * * * wget *.herokuapp.com
像上面那上给个定时任务，我路由器是被我刷成了OpenWrt的，上面就有定时任务，你要是没有这样的路由器，那可以给你其他的vps加上任务一样搞定。

**Comment by Nicolas-Gong** [comment]
> > > @Nicolas-Gong 我最近发现，如果长时间不用heroku app & tunnel 不会从休眠回来，会挂掉，需要重新部署。。不知道你遇到过吗？
> > 
> > 
> > 第一天我就遇到这个问题了，我以为你自己解决了。。。其实很简单我是放在路由，每隔29分钟访问一次heroku给的链接 */29 * * * * wget *.herokuapp.com 像上面那上给个定时任务，我路由器是被我刷成了OpenWrt的，上面就有定时任务，你要是没有这样的路由器，那可以给你其他的vps加上任务一样搞定。
> 
> 嗯，甚至可以写个github action然后按照cron 触发。。但是一般不带tunnel的app，一般会从休眠中恢复。。。我不经常用，所以不确定。。

heroku有个机制，就是会自己休眠，30分钟你不访问下，就会睡死下去，通过tunnel是访问是无法唤醒的，只能直接访问heroku的链接，以前可以用wokers的链接访问是能唤醒的，但是tunnel就不行了，你只需要第29分钟时访问下就可以续一秒了

**Comment by zizifn** [comment]
> > > > @Nicolas-Gong 我最近发现，如果长时间不用heroku app & tunnel 不会从休眠回来，会挂掉，需要重新部署。。不知道你遇到过吗？
> > > 
> > > 
> > > 第一天我就遇到这个问题了，我以为你自己解决了。。。其实很简单我是放在路由，每隔29分钟访问一次heroku给的链接 */29 * * * * wget *.herokuapp.com 像上面那上给个定时任务，我路由器是被我刷成了OpenWrt的，上面就有定时任务，你要是没有这样的路由器，那可以给你其他的vps加上任务一样搞定。
> > 
> > 
> > 嗯，甚至可以写个github action然后按照cron 触发。。但是一般不带tunnel的app，一般会从休眠中恢复。。。我不经常用，所以不确定。。
> 
> heroku有个机制，就是会自己休眠，30分钟你不访问下，就会睡死下去，通过tunnel是访问是无法唤醒的，只能直接访问heroku的链接，以前可以用wokers的链接访问是能唤醒的，但是tunnel就不行了，你只需要第29分钟时访问下就可以续一秒了

了解了。+1s.....
