### ISSUE TITLE
想问一下现在的代码状态能否部署到CF pages

### ISSUE THREAD

**Issue by egg1234** [zizifn/v2ray-heroku#160]
如果能够的话是怎样的流程

谢谢！

**Comment by zizifn** [comment]
由于大家反馈 pages 部署过于麻烦，然后 pages 我删除。等 bug fix 完后，再考虑，目前没有考虑。

**Comment by qhgy** [comment]
不算麻烦 挺好的 感谢大佬🧍‍♂️

**Comment by rikkagcp1** [comment]
可以用pages转发到worker:

https://github.com/rikkagcp1/cf_pages_forward

**Comment by zizifn** [comment]
> @zizifn 谢谢耐心提点！ 的确能用，之前是我太老实了，看见粘贴后出错就没去试用了
> 
> 但在部署过程中有一些问题还是不明白，需要请教
> 
> 首先是粘贴后点“save and deploy”，点完后按钮会一直变灰，不会完成，与一般的workers点“save and deploy”会自己完成不一样，需要点左上的项目名称强迫返回，但这时的确能用
> 
> 但在点左上的项目名称强迫返回前点“preview”会出现web页面变成下面的输出了，这个不知有没有泄漏自己信息的问题，而且在别的地方再访问这个workers的页面也是下面的输出了，当然这个输出的内容会随访问来源地点会改变一些
> 
> {"clientTcpRtt":11,"longitude":"-95.85170","latitude":"41.25910","tlsCipher":"AEAD-AES128-GCM-SHA256","continent":"NA","asn":396982,"clientAcceptEncoding":"gzip, deflate, br","country":"US","tlsClientAuth":{"certIssuerDNLegacy":"","certIssuerSKI":"","certSubjectDNRFC2253":"","certSubjectDNLegacy":"","certFingerprintSHA256":"","certNotBefore":"","certSKI":"","certSerial":"","certIssuerDN":"","certVerified":"NONE","certNotAfter":"","certSubjectDN":"","certPresented":"0","certRevoked":"0","certIssuerSerial":"","certIssuerDNRFC2253":"","certFingerprintSHA1":""},"tlsExportedAuthenticator":{"clientFinished":"1234578c57023a0767eb654678aaf35e34e7b7eb57aab740bca28e398ad12345","clientHandshake":"12345b0bc2ea6d4b52045d6c9112387e46e59bf0111ec3a8b2a2273f2ea12345","servero","city":"Council Bluffs","edgeRequestKeepAliveStatus":1,"requestPriority":"weight=42;exclusive=0;group=13;group-weight=241","httpProtocol":"HTTP/2","region":"Iowa","regionCode":"IA","asOrganization":"Google Cloud","metroCode":"652","postalCode":"51502","botManagement":{"corporateProxy":false,"verifiedBot":false,"jsDetection":{"passed":false},"staticResource":false,"detectionIds":{},"score":99}}

这个是访问者和服务器沟通的信息。一般没有安全问题，但是也不要给别人看。
