### ISSUE TITLE
[Feature Request] 能否让用户自己修改web页面显示

### ISSUE THREAD

**Issue by egg1234** [zizifn/v2ray-heroku#164]
现在版本的web页面显示的是浏览器与服务器交互的信息，能否让用户自己修改这个web页面的显示，哪怕是只显示为用户自己写的一句话

谢谢！

**Comment by zizifn** [comment]
> 现在版本的web页面显示的是浏览器与服务器交互的信息，能否让用户自己修改这个web页面的显示，哪怕是只显示为用户自己写的一句话
> 
> 谢谢！

你这个代码不是随便改？

**Comment by zizifn** [comment]
> js的代码一窍不通，让你见笑了

等我有时间写个注释。主页没意义的。

**Comment by Su-yj** [comment]
虽然不知道黑盒会做些什么，但能掩饰还是做一下比较好点吧？
