### ISSUE TITLE
使用新的worker-with-socks5-experimental.js代码设置socks5代理后CF托管网站永远等待连接

### ISSUE THREAD

**Issue by egg1234** [zizifn/v2ray-heroku#179]
使用新的worker-with-socks5-experimental.js代码设置socks5代理后，访问CF托管的网站不断显示“检查站点连接是否安全”，即使之后点击了“我是人类”的框框，还是继续等待连接而不会显示网站的内容

**Comment by s1q0** [comment]
That's related to the proxy server. Try changing it.
这与代理服务器有关。 尝试改变它。
