### ISSUE TITLE
该项目（之前已部署完成），但现在提示 Cloudflare tunnel 需要更细，请作者指点一下（如何对已部署的项目进行组件更新）。

### ISSUE THREAD

**Issue by lan-rone** [zizifn/v2ray-heroku#23]
heroku 项目/    More/   View logs/

摘取部分log到下方
WRN Your version 2022.5.0 is outdated. We recommend upgrading it to 2022.5.1

请作者指点一下如何使用，已部署的该项目自带的网页控制台 （heroku 项目/   More/   Run console），使用命令进行更新组件。

谢谢作者能给予帮助，再次谢谢！

**Comment by zizifn** [comment]
> heroku 项目/ More/ View logs/
> 
> 摘取部分log到下方 WRN Your version 2022.5.0 is outdated. We recommend upgrading it to 2022.5.1
> 
> 请作者指点一下如何使用，已部署的该项目自带的网页控制台 （heroku 项目/ More/ Run console），使用命令进行更新组件。
> 
> 谢谢作者能给予帮助，再次谢谢！

cloud tunnel 时常更新。如果提升更新，你就重新用github action 部署一遍就可以。。
