### ISSUE TITLE
项目无法使用

### ISSUE THREAD

**Issue by dfmjndm** [zizifn/v2ray-heroku#25]
用了一段时间突然连不上了，检查不出问题，
重新部署出现警告
![image](https://user-images.githubusercontent.com/57401901/168987864-28487ec4-ff72-4b08-bda3-850530889a04.png)

**Comment by dfmjndm** [comment]
测试情况，在自己的fork，已经删除v2ray字样

**Comment by redebugzzh** [comment]
遇到同样的情况，也是fork到自己的项目库，名称里也不包含任何v2ray，错误提示与楼上一样

**Comment by zizifn** [comment]
> 测试情况，在自己的fork，已经删除v2ray字样

这种情况就必须用github action 部署啦。

**Comment by zizifn** [comment]
> 遇到同样的情况，也是fork到自己的项目库，名称里也不包含任何v2ray，错误提示与楼上一样

这种情况就必须使用github action 部署啦。

**Comment by zizifn** [comment]
或者尝试把app.json里面的repo 删除。。。

**Comment by redebugzzh** [comment]
> 或者尝试把app.json里面的repo 改成空字符（最新code已经改了）。。。

action  部署成功

**Comment by dfmjndm** [comment]
> > 或者尝试把app.json里面的repo 改成空字符（最新code已经改了）。。。
> 
> action  部署成功

![Screenshot_2022-05-20-18-44-49-059_com.android.chrome.png](https://user-images.githubusercontent.com/57401901/169512000-677f4721-2158-4da7-98bc-804105e23225.png)

action部署也不行

**Comment by zizifn** [comment]
> > > 或者尝试把app.json里面的repo 改成空字符（最新code已经改了）。。。
> > 
> > 
> > action  部署成功
> 
> ![Screenshot_2022-05-20-18-44-49-059_com.android.chrome.png](https://user-images.githubusercontent.com/57401901/169512000-677f4721-2158-4da7-98bc-804105e23225.png)
> 
> action部署也不行

要么你APIkey或者Email配错。请网页登陆heroku成功后，重新配置一次github action的sercet。

**Comment by zhengyu19790319** [comment]
完全不行了，我的账号也被disable了
