### ISSUE TITLE
CloudFlare Workers 被墙解决方案

### ISSUE THREAD

**Issue by dfireworks** [zizifn/v2ray-heroku#27]
https://owo.misaka.rest/cf-workers-ban-solution/
教程地址
在昨晚上，某个你们熟悉的玩意把CloudFlare Workers的玉米（workers.dev）给全线屏蔽了。这下对于我们有使用Heroku的单双号Workers脚本有很大的不便。今天的这篇教程就来和大家一起解决这个问题

准备材料
一枚域名
一个目前运行状态正常的Worker
部署步骤
登录至你的CloudFlare账号，选择你自己的域名
进入DNS选项，按照下图解析CMANE你的域名到Workers，打开小云朵
![47c8df79f81a8735de5c981b5a44ff02_20220509182528](https://user-images.githubusercontent.com/105620366/169540175-68c0bb4b-f67a-4ffa-8c27-494e0a6dfc1f.png)

然后转到Workers，配置Workers路由

![59c2fb75cb8e3a21c7bc5e8b4e185281_20220509182629](https://user-images.githubusercontent.com/105620366/169540216-cadaf101-5940-4734-b66d-25cf8bf3f1d5.png)

按照下图配置

![6b16ee99b8339a3e308090894af7d6b6_20220509182713](https://user-images.githubusercontent.com/105620366/169540266-97329c22-fbc3-40f4-8808-e9ae5421e406.png)

Workers转发就设置完成了
接下来去一个字母叫V开头的软件，把Workers.dev域名换成你自己的域名
![2a1db5ad8d1b48b702630e606938a1eb_20220509182750](https://user-images.githubusercontent.com/105620366/169540319-20d7d409-5706-45ea-bdd4-59d79b9cf630.png)

见证奇迹的时刻发生了
建议开发者置顶

**Comment by zizifn** [comment]
谢谢。置顶的issue  已经包含 https://owo.misaka.rest/cf-workers-ban-solution/ 和您的解决方案类似。

**Comment by dfireworks** [comment]
> 谢谢。置顶的issue 已经包含 https://owo.misaka.rest/cf-workers-ban-solution/ 和您的解决方案类似。

这个就是他的 只是看到了顺手发了一下

**Comment by EasongChung** [comment]
我用免费域名试了不行了，网页访问地址有5秒调整，是不是这个原因？

**Comment by zizifn** [comment]
> 我用免费域名试了不行了，网页访问地址有5秒调整，是不是这个原因？

5秒调整什么意思?

**Comment by EasongChung** [comment]
上面打错字是指5秒盾，我关了5秒盾就可以使用了。

**Comment by zizifn** [comment]
> 上面打错字是指5秒盾，我关了5秒盾就可以使用了。

5秒盾指的是?

**Comment by zizifn** [comment]
> 上面打错字是指5秒盾，我关了5秒盾就可以使用了。

5秒盾指的是?

**Comment by EasongChung** [comment]
> > 上面打错字是指5秒盾，我关了5秒盾就可以使用了。
> 
> 5秒盾指的是?

就是Under Attack 模式，开启后访问你的域名站点会有5秒防护验证。
