### ISSUE TITLE
部署到heroku后尝试ping部署的地址 超时

### ISSUE THREAD

**Issue by 287857652** [zizifn/v2ray-heroku#3]
按着教程部署后，填入地址等信息  协议选的ws   uuid自己生成并且改了heroku的环境变量  
但是配置v2ray后，尝试使用 发现无法使用
ping了一下地址也是超时的，请问咋办
因为ping是timeout所以后面的cloudflare也没有弄了

**Comment by zizifn** [comment]
等我一会上线看你的repo.

**Comment by 287857652** [comment]
> 等我一会上线看你的repo.

感谢

**Comment by zizifn** [comment]
> > 等我一会上线看你的repo.
> 
> 感谢

你的herkou的app，名字是什么？

**Comment by 287857652** [comment]
> > > 等我一会上线看你的repo.
> > 
> > 
> > 感谢
> 
> 你的herkou的app，名字是什么？

bingo11

**Comment by zizifn** [comment]
> > 等我一会上线看你的repo.
> 
> 感谢

你可以登陆到herkou 看下log，是否deploy 成功？

**Comment by 287857652** [comment]
> > > 等我一会上线看你的repo.
> > 
> > 
> > 感谢
> 
> 你可以登陆到herkou 看下log，是否deploy 成功？

log在哪里看 我进入heroku只看到bingo11的一个容器

**Comment by zizifn** [comment]
> > > > 等我一会上线看你的repo.
> > > 
> > > 
> > > 感谢
> > 
> > 
> > 你可以登陆到herkou 看下log，是否deploy 成功？
> 
> log在哪里看 我进入heroku只看到bingo11的一个容器

![image](https://user-images.githubusercontent.com/1803942/128029150-9b2351a4-281f-42a0-8882-a4c5a8c21778.png)

**Comment by zizifn** [comment]
> > > > > 等我一会上线看你的repo.
> > > > 
> > > > 
> > > > 感谢
> > > 
> > > 
> > > 你可以登陆到herkou 看下log，是否deploy 成功？
> > 
> > 
> > log在哪里看 我进入heroku只看到bingo11的一个容器
> 
> ![image](https://user-images.githubusercontent.com/1803942/128029150-9b2351a4-281f-42a0-8882-a4c5a8c21778.png)

我认为你的app 没有问题，你在确认下log 里面有没有错误。https://bingo11.herokuapp.com/  可能是你客户端的问题

**Comment by 287857652** [comment]
> > > > > > 等我一会上线看你的repo.
> > > > > 
> > > > > 
> > > > > 感谢
> > > > 
> > > > 
> > > > 你可以登陆到herkou 看下log，是否deploy 成功？
> > > 
> > > 
> > > log在哪里看 我进入heroku只看到bingo11的一个容器
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/1803942/128029150-9b2351a4-281f-42a0-8882-a4c5a8c21778.png)
> 
> 我认为你的app 没有问题，你在确认下log 里面有没有错误。https://bingo11.herokuapp.com/ 可能是你客户端的问题

2021-08-03T14:05:16.171511+00:00 heroku[router]: at=info method=GET path="/" host=bingo11.herokuapp.com request_id=9fcdc6e5-cbb1-49d3-8c1c-db46b49e65e7 fwd="XXX.1.XXX.143,172.69.98.125" dyno=web.1 connect=1ms service=12664ms status=101 bytes=129 protocol=https

这是我刚刚的log  里面的XXX是我打上去的 打个码，app应该没问题  
客户端是刚刚去github下载的v2ray-core   版本4.20
我客户端ping显示time out，我就用cmd   ping，也是超时

**Comment by zizifn** [comment]
> > > > > > > 等我一会上线看你的repo.
> > > > > > 
> > > > > > 
> > > > > > 感谢
> > > > > 
> > > > > 
> > > > > 你可以登陆到herkou 看下log，是否deploy 成功？
> > > > 
> > > > 
> > > > log在哪里看 我进入heroku只看到bingo11的一个容器
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/1803942/128029150-9b2351a4-281f-42a0-8882-a4c5a8c21778.png)
> > 
> > 
> > 我认为你的app 没有问题，你在确认下log 里面有没有错误。https://bingo11.herokuapp.com/ 可能是你客户端的问题
> 
> 2021-08-03T14:05:16.171511+00:00 heroku[router]: at=info method=GET path="/" host=bingo11.herokuapp.com request_id=9fcdc6e5-cbb1-49d3-8c1c-db46b49e65e7 fwd="XXX.1.XXX.143,172.69.98.125" dyno=web.1 connect=1ms service=12664ms status=101 bytes=129 protocol=https
> 
> 这是我刚刚的log 里面的XXX是我打上去的 打个码，app应该没问题
> 客户端是刚刚去github下载的v2ray-core 版本4.20
> 我客户端ping显示time out，我就用cmd ping，也是超时

把你的UUID 给我，我试试看。记得以后改掉

**Comment by zizifn** [comment]
@287857652 还有你的github action，估计 你di第一个填错了，导致你action deploy 有个错误。我认为你目前的heroku的app 没有问题。 我要睡觉了。有问题留言。
![image](https://user-images.githubusercontent.com/1803942/128033696-2abac811-111f-4fd0-ae75-0fc343d58c13.png)

**Comment by 287857652** [comment]
> @287857652 还有你的github action，估计 你第一个填错了，导致你action deploy 有个错误。我认为你目前的heroku的app 没有问题。 我要睡觉了。有问题留言。
> ![image](https://user-images.githubusercontent.com/1803942/128033696-2abac811-111f-4fd0-ae75-0fc343d58c13.png)

感谢，我再试试

**Comment by 287857652** [comment]
> > > > > > > > 等我一会上线看你的repo.
> > > > > > > 
> > > > > > > 
> > > > > > > 感谢
> > > > > > 
> > > > > > 
> > > > > > 你可以登陆到herkou 看下log，是否deploy 成功？
> > > > > 
> > > > > 
> > > > > log在哪里看 我进入heroku只看到bingo11的一个容器
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/1803942/128029150-9b2351a4-281f-42a0-8882-a4c5a8c21778.png)
> > > 
> > > 
> > > 我认为你的app 没有问题，你在确认下log 里面有没有错误。https://bingo11.herokuapp.com/ 可能是你客户端的问题
> > 
> > 
> > 2021-08-03T14:05:16.171511+00:00 heroku[router]: at=info method=GET path="/" host=bingo11.herokuapp.com request_id=9fcdc6e5-cbb1-49d3-8c1c-db46b49e65e7 fwd="XXX.1.XXX.143,172.69.98.125" dyno=web.1 connect=1ms service=12664ms status=101 bytes=129 protocol=https
> > 这是我刚刚的log 里面的XXX是我打上去的 打个码，app应该没问题
> > 客户端是刚刚去github下载的v2ray-core 版本4.20
> > 我客户端ping显示time out，我就用cmd ping，也是超时
> 
> 把你的UUID 给我，我试试看。记得以后改掉
我刚刚试了试 虽然ping超时了，但是竟然有0.3M的速度  套上cloudflare有4M左右

**Comment by playnetcn** [comment]
@zizifn heroku不要删除重新部署，删除重新部署网络就不通了，原来已部署好的不删除就没问题。可能是做了技术限制。删除重新部署只能用套上cloudflare。

**Comment by zizifn** [comment]
你是说，使用 github action 重新部署后， Heroku会连接不上不通？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月14日(周六) 晚上10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zizifn/v2ray-heroku] 部署到heroku后尝试ping部署的地址 超时 (#3)




 
@zizifn heroku不要删除重新部署，删除重新部署网络就不通了，原来已部署好的不删除就没问题。可能是做了技术限制。删除重新部署只能用套上cloudflare。

**Comment by playnetcn** [comment]
@zizifn 今天我试了一下，我原来有三个项目名称，我删除了一个，再重新部署，新部署的网络就不通了，但是原来部署好的，使用是没问题的。github上面任何一个v2ray项目部署到heroku上面默认网络都不通。只能用cf来使用部署的应用。
