### ISSUE TITLE
我部署成功了，也可以看见小猫，可是就是不能使用，求指教

### ISSUE THREAD

**Issue by pt4lwj** [zizifn/v2ray-heroku#33]
<img width="597" alt="WechatIMG1308" src="https://user-images.githubusercontent.com/10663197/170816989-5cd9cedd-1732-4202-bfeb-fba5c3904dc9.png">
另外我使用的是V2RayU
不知道这样设置是否正确

**Comment by zizifn** [comment]
1. 确保自己uuid不要输入错。想验证可以登录到herokuapp 网站。
2. 把ws的host删除掉?

**Comment by pt4lwj** [comment]
1.uuid没问题
2.ws这块host删除 还是不行😖

**Comment by zizifn** [comment]
> 1.uuid没问题
> 2.ws这块host删除 还是不行😖

我看不到你的配置有什么问题，实在不行，在github action的sercert中换个uuid，在重新deploy一次。

**Comment by zizifn** [comment]
看到首页一般基本代表启动成功。

**Comment by zizifn** [comment]
当然如果你愿意等，今晚我会发布一版新的，首页每次部署都会变得版本。

**Comment by zizifn** [comment]
> 当然如果你愿意等，今晚我会发布一版新的，首页每次部署都会变得版本。而且wspath和首页path是一致的。

**Comment by pt4lwj** [comment]
那太好了 我坐等今晚新版本
之前搞的我其中一个账号被封掉了
我还写了邮件申诉
<img width="760" alt="WechatIMG1310" src="https://user-images.githubusercontent.com/10663197/170819286-936c809b-9dff-4199-8b40-9bf1d3e1a414.png">

**Comment by zizifn** [comment]
> 那太好了 我坐等今晚新版本 之前搞的我其中一个账号被封掉了 我还写了邮件申诉 <img alt="WechatIMG1310" width="760" src="https://user-images.githubusercontent.com/10663197/170819286-936c809b-9dff-4199-8b40-9bf1d3e1a414.png">

原则上搭建proxy server的确违法了他们的user agreement。。封号与否看命，但是目前虽然有封号，但是很多人的都正常。看herokuapp的力度吧。

**Comment by zizifn** [comment]
> 那太好了 我坐等今晚新版本 之前搞的我其中一个账号被封掉了 我还写了邮件申诉 <img alt="WechatIMG1310" width="760" src="https://user-images.githubusercontent.com/10663197/170819286-936c809b-9dff-4199-8b40-9bf1d3e1a414.png">

已经更新，你拉去最近代码，然后试试，记得看下readme，配置章节。

**Comment by casualtouch** [comment]
path改成/  去掉ws试试 我昨天也遇到了 但是改了路径就可以了

**Comment by zizifn** [comment]
close as no response.
