### ISSUE TITLE
从vless转到vmess后无法使用

### ISSUE THREAD

**Issue by Nicolas-Gong** [zizifn/v2ray-heroku#35]
`{
	"inbounds": [
		{
			"port": $PORT,
			"listen": "localhost",
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "$UUID",
						"alterId": 0
					}
				]
			},
			"streamSettings": {
				"network": "ws",
				"wsSettings": {
					"path": "/"
				}
			}
		}
	],
	"outbounds": [
		{
			"protocol": "freedom",
			"settings": {}
		}
	]
}`

最近还是想切换会vmess，就尝试在`improve-tunnel`分支下仅修改了`startup.sh`的配置文件为vmess，如上所示，部署成功了，但是访问heroku的链接后总是Application error。换了我其它vps上的配置文件都不行，不知道是哪里还需要操作？

**Comment by zizifn** [comment]
> `{ "inbounds": [ { "port": $PORT, "listen": "localhost", "protocol": "vmess", "settings": { "clients": [ { "id": "$UUID", "alterId": 0 } ] }, "streamSettings": { "network": "ws", "wsSettings": { "path": "/" } } } ], "outbounds": [ { "protocol": "freedom", "settings": {} } ] }`
> 
> 最近还是想切换会vmess，就尝试在`improve-tunnel`分支下仅修改了`startup.sh`的配置文件为vmess，如上所示，部署成功了，但是访问heroku的链接后总是Application error。换了我其它vps上的配置文件都不行，不知道是哪里还需要操作？

tunnel 有点问题。。等会PR。。。

**Comment by Nicolas-Gong** [comment]
我没用`main`分支，`improve-tunnel`这个分支的tunnel是没有问题的，可以用，但是换成vmess就不行了。

**Comment by zizifn** [comment]
> 我没用`main`分支，`improve-tunnel`这个分支的tunnel是没有问题的，可以用，但是换成vmess就不行了。

等我试试。。

**Comment by zizifn** [comment]
> 我没用`main`分支，`improve-tunnel`这个分支的tunnel是没有问题的，可以用，但是换成vmess就不行了。

请拉去最近code， master branch 就可以。。如果想要vmess，看下try-vmess branch...

**Comment by Nicolas-Gong** [comment]
> > 我没用`main`分支，`improve-tunnel`这个分支的tunnel是没有问题的，可以用，但是换成vmess就不行了。
> 
> 请拉去最近code， `main` branch 就可以。。如果想要vmess，看下try-vmess branch...

ok，可以了，居然仅仅只是改了协议就可以了。。。大吃一斤

**Comment by zizifn** [comment]
> > > 我没用`main`分支，`improve-tunnel`这个分支的tunnel是没有问题的，可以用，但是换成vmess就不行了。
> > 
> > 
> > 请拉去最近code， `main` branch 就可以。。如果想要vmess，看下try-vmess branch...
> 
> ok，可以了，居然仅仅只是改了协议就可以了。。。大吃一斤

我也不知道，tunnel 貌似default用 http3 的 quic， 貌似泛用性不够，有时候抽风。。
