### ISSUE TITLE
建议：使用更好的伪装

### ISSUE THREAD

**Issue by BakaJzon** [zizifn/v2ray-heroku#39]
<https://paper-3.io/> <https://iogames.space/>
长效连接的网站除了 bypas-s 之外也没有很多
可以~~逝世~~试试用游戏网站做伪装

**Comment by zizifn** [comment]
> https://paper-3.io/ https://iogames.space/ 长效连接的网站除了 bypas-s 之外也没有很多 可以~逝世~试试用游戏网站做伪装

算了，要是heroku以后十分严格，那就寻另外的。只有有人提供免费 pass 或者sass服务，很容易把软件弄上去的。
