### ISSUE TITLE
建议：方便管理APP

### ISSUE THREAD

**Issue by QvbBlt** [zizifn/v2ray-heroku#40]
1. 搭建APP的时候，如果APP_NAME留空，程序会自动创建名称，但是在github上面没法查看app的名称，需要到heroku上面看不方便，如果GitHub上能看，麻烦说一下，谢谢！如果不能看能否添加这个功能？

2. Github Actions 界面每执行一次就会多出一条信息，如果执行多次尤其是多账号管理，没有登记号APP名称后期无法在GitHub上管理APP，能添加管理APP的功能吗？就是我利用github actions部署了多少有效APP，名称是什么，是哪几个账号下面的，APP现在是停止还是启动的。不知这种需求能实现吗？

**Comment by QvbBlt** [comment]
> 要实现是可以的，因为heroku的cli是可以获取这些信息的。可以写一个action，跑一下就回来heroku账户的所有信息。。但是action是公开的，任何人都可以看到你的action 输出log。所以，第一个我可以考虑下，第二个我不会去做。

怎么能避免公开app名称呢？第二个需求，如果把项目变成私有是不是就能避免了？还有其他方法能得到heroku账户信息但是又不公开信息？

**Comment by zizifn** [comment]
> 
> > 要实现是可以的，因为heroku的cli是可以获取这些信息的。可以写一个action，跑一下就回来heroku账户的所有信息。。但是action是公开的，任何人都可以看到你的action 输出log。所以，第一个我可以考虑下，第二个我不会去做。
> 
> 怎么能避免公开app名称呢？第二个需求，如果把项目变成私有是不是就能避免了？还有其他方法能得到heroku账户信息但是又不公开信息？

私有repo就可以。github secret 配置app name，log会mask。。。这就是文档为什么要配置到secret。

**Comment by QvbBlt** [comment]
可以帮我写一下action，可以输出“利用github actions部署了多少有效APP，名称是什么，是哪几个账号下面的，APP现在是停止还是启动的”，我想私有repo，自己使用，
你建议这样操作吗？私有repo之后还有泄露的风险吗？如果你帮我写了了这个action，后期你更新了项目，我又如何修改项目能跟随你的新项目，学习这些内容有哪些参考文档呢？纯小白，求指教，想学习一下这方面的知识。

**Comment by zizifn** [comment]
> 可以帮我写一下action，可以输出“利用github actions部署了多少有效APP，名称是什么，是哪几个账号下面的，APP现在是停止还是启动的”，我想私有repo，自己使用， 你建议这样操作吗？私有repo之后还有泄露的风险吗？如果你帮我写了了这个action，后期你更新了项目，我又如何修改项目能跟随你的新项目，学习这些内容有哪些参考文档呢？纯小白，求指教，想学习一下这方面的知识。 写action是不是像添加HEROKU_TUNNEL_TOKEN，标记为可选，设置false和true，控制它是否执行？

私有repo同步我的给更新不是和你明了，但是如果你会Git 命令，可以做到。
管理app功能有个问题，action 只能读取当前环境的secret，所以action只能获取到当前环境的heroku api key。。

但是我们可以单独创建一个环境，这个环境只配置heroku api sercert，这样action就可以循环heroku api sercert，得到所以heroku 账户信息。

至于资料，如果你熟悉任何cicd的tool，你可以Google github action就可以看到文档，heroku cli也有文档，只有heroku cli 可以做到，action都可以做。

**Comment by zizifn** [comment]
如果你同意单独创建一个环境查看所有app，我可以简单写个例子。但是不会写到readme里面。

但是我可以增强现在action，加个选项，输出heroku 账户所有app 的状态。在这个选项说明，会泄露app名字，使用风险自控。

**Comment by QvbBlt** [comment]
查看email
