### ISSUE TITLE
iOS能科学上网，电脑却不行

### ISSUE THREAD

**Issue by zhere** [zizifn/v2ray-heroku#41]
目前出现两个问题：
1.iOS小火箭配置好后可以科学上网，但今天经常有时候能连上，有时候就连不上，请问 有什么方法解决一下？
2.手机上配置能科学上网，但Windows电脑按照页面上v2RAY N的配置方法 配置 cloudflare worker 里dev的地址等 仍然无法连上，连接测延时提示timeout （ 有自己的域名）
麻烦大佬看看，谢谢！

**Comment by zizifn** [comment]
只要***. herokuapp.com 访问正常，就可以连上。隐去信息，配置发上来。

**Comment by zhere** [comment]
![捕获](https://user-images.githubusercontent.com/7373748/171076540-f5ddcb47-e906-4b20-ae9f-db8e32f5f09c.PNG)

**Comment by zizifn** [comment]
worker域名不好用，参考下面文档
https://owo.misaka.rest/cf-workers-ban-solution/

如果完成上面文档，
1. 输入自己域名到浏览器，看看是否返回首页
2. 把地址改成自己域名，不是worker地址 如果你有workerIP，就把他改成IP

**Comment by zhere** [comment]
已在worker里配置好自己的域名。
1.自己域名能返回首页；2. v2rayN里 也都配置好了，可还是连不上 ；报错如下：
2022/05/31 21:43:57 [Warning] [1027887627] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://a.yellowzhree.ml/):  > write tcp 192.168.10.229:54613->172.68.176.142:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://a.y********e.ml/):  > write tcp 192.168.10.229:54646->172.68.176.142:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://a.y********e.ml/):  > write tcp 192.168.10.229:54672->172.67.166.142:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://a.y********e.ml/):  > dial tcp 172.68.176.142:443: operation was canceled transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://a.y********e.ml/):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed
![捕获3](https://user-images.githubusercontent.com/7373748/171189067-6a58d117-c7f8-4b4b-a90d-2a4b0ae1e296.PNG)

**Comment by zizifn** [comment]
> 已在worker里配置好自己的域名。 1.自己域名能返回首页；2. v2rayN里 也都配置好了，可还是连不上 ；报错如下： 2022/05/31 21:43:57 [Warning] [1027887627] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://a.yellowzhree.ml/): > write tcp 192.168.10.229:54613->172.68.176.142:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://a.y********e.ml/): > write tcp 192.168.10.229:54646->172.68.176.142:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://a.y********e.ml/): > write tcp 192.168.10.229:54672->172.67.166.142:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://a.y********e.ml/): > dial tcp 172.68.176.142:443: operation was canceled transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://a.y********e.ml/): > dial tcp: operation was canceled] > common/retry: all retry attempts failed ![捕获3](https://user-images.githubusercontent.com/7373748/171189067-6a58d117-c7f8-4b4b-a90d-2a4b0ae1e296.PNG)

伪装域名不对。你写成path了。。。

**Comment by zhere** [comment]
感谢，已经能科学上网了。 
还麻烦问一下 ，有什么办法解决 同样的配置，win10 看YouTube 慢，手机却很快的问题么？   Google了一圈 有说重置 设置的，照做了，还是不管用， 您这边有什么好的方法不

**Comment by zizifn** [comment]
> 感谢，已经能科学上网了。 还麻烦问一下 ，有什么办法解决 同样的配置，win10 看YouTube 慢，手机却很快的问题么？ Google了一圈 有说重置 设置的，照做了，还是不管用， 您这边有什么好的方法不

如果手机电脑使用的我服是一样的话，一般速度是一样的。要不把v2rayN 升级下?

**Comment by zhere** [comment]
哈哈，原来如此。

**Comment by zhere** [comment]
刚更新了v2rayN  V5.25客户端 , 看了1080PYouTube， 结果 看了没几分钟 就断开了，Google网页 都打不开了。。。 报错如下：
![捕获6](https://user-images.githubusercontent.com/7373748/171320660-64ac3ed4-db1b-4b74-afea-f921d6d74fe0.PNG)

（我 刚使用 V2rayN测过速，会不会跟这个有关系；  heroku账号是正常的）

**Comment by zhere** [comment]
好的，我试试

**Comment by zizifn** [comment]
> 好的，我试试

如果你家宽带直连heroku速度可以，可以直连。没必要cloudflare。。。
