### ISSUE TITLE
我的heroku账号又被封了，已经封了5-6个了尴尬

### ISSUE THREAD

**Issue by oldworship** [zizifn/v2ray-heroku#42]

**Comment by zhere** [comment]
用的是最新的库 部署吗？
未用 大佬们 最新的库 部署，被封了2次；目前使用最新的库 按照页面提示进行手动部署，手机正常运行几天了。

**Comment by zizifn** [comment]
现在封号是玄学，我不知道规则，拉取最新代码试试吧。

**Comment by zizifn** [comment]
可以玄学下，把heroku 账号加上 2fa吧。

**Comment by oldworship** [comment]
用的最新的代码建的，用了3天把，又被封了，之前的代码，3个小时就被封了

**Comment by oldworship** [comment]
> 

对啊，用的最新的部署的，用了3天，号没了

**Comment by oldworship** [comment]
>我试试加上2fa

**Comment by zizifn** [comment]
如果还被封，我就试试彻底不用v2fly 官方镜像，采用从 linux package 安装。。

**Comment by redebugzzh** [comment]
用的最新代码，依然3天后被封，很邪门，还有几个账号，部署的都是以前老版本和其他版本的v2ray，只要不使用，一点问题都没有，但只要用了，基本上3天就封号，感觉似乎不是安装方式的问题。

**Comment by dfbucy090** [comment]
再观察几天，老版本部署的陆续在封，最新的好像还正常

**Comment by thebifrost** [comment]
新的也被封了0.0

**Comment by oldworship** [comment]
应该是跟你上网选择的网络有关。在heroku封号之前，我用的共享网络（可能这个时候就记住了你的ip或者其他，不太懂），封号之后我用新代码只要用共享网络就封号，用自己的手机网络就没事，具体不知道跟网络有关还是跟IP有关。

**Comment by 362227** [comment]
就是走大流量的被封了，我很多项目的都被封了，只要涉及下载和上传，而且这个限制很严格，好像长时间（几分钟都算）跑2M/S
以上都会被封

**Comment by oldworship** [comment]
over
