### ISSUE TITLE
 VLESS 协议能更改吗？？

### ISSUE THREAD

**Issue by kitkw** [zizifn/v2ray-heroku#45]
搭建好才发现openclash 不能用 VLESS 协议.........。如何改vmess

**Comment by zizifn** [comment]
你可以自己修改自己repo里面的 文件。
https://github.com/zizifn/v2ray-heroku/blob/main/config.json.tp#L24

**Comment by kitkw** [comment]
成功👌👌感谢回复小白问题👍👍
