### ISSUE TITLE
现在actions好像部署不了，在deploy这一步失败

### ISSUE THREAD

**Issue by UncleZhang1990** [zizifn/v2ray-heroku#47]
报错如下：

Run akhileshns/heroku-deploy@v3.12.12
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Successfully logged into heroku
 ›   Error: You do not have access to the app ***.
 ›
 ›   Error ID: forbidden
Creating ***... !
 ▸    Name *** is already taken
Error: Error: Command failed: heroku create *** --region us
Creating ***... !
 ▸    Name *** is already taken

**Comment by zizifn** [comment]
Name *** is already taken。。你的APP名字不唯一。。

**Comment by UncleZhang1990** [comment]
> Name *** is already taken。。你的APP名字不唯一。。

感谢，现在ok了
