### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by fangxingweiai** [zizifn/v2ray-heroku#6]
## fork完并修改了一些配置如下：

- app.json文件
  ```json
  {
    "name": "V2Ray",
    "description": "Deploy V2ray on Heroku.",
    "keywords": [
        "V2Ray"
    ],
    "env": {
        "UUID": {
            "description": "V2Ray UUID",
            "value": "ce7ea10b-5b27-49ab-a93d-6b184df9cce9"
        },
        "AID": {
            "description": "V2Ray AlterID",
            "value": 0
        }
    },
    "website": "https://github.com/zizifn/v2ray-heroku",
    "repository": "https://github.com/zizifn/v2ray-heroku",
    "stack": "container"
  }
  ```
 
- startup.sh文件
  ``` json
  "inbounds": [
        {
            "port": $PORT,
            "protocol": "vmess",
            "settings": {
                "clients": [
                    {
                        "id": "$UUID",
                        "level": 0,
                        "alterId": $AID
                    }
                ],
                 "decryption": "none"
            },
            "streamSettings": {
                "network": "ws",
                "allowInsecure": false,
                "wsSettings": {
                    "path": "/$UUID-vmess"
                }
            }
        }
    ]
  ```
- main.yml文件
  更新了版本 akhileshns/heroku-deploy@v3.12.12

## 建立 Environments部署时报的错
![image](https://user-images.githubusercontent.com/62201630/144632809-15f027fc-b419-4c7d-b2aa-3558ec9266bc.png)

**Comment by zizifn** [comment]
请确保自己sercert 在仓库setting配置了，比如APP名字，heroku的api key，具体请看readme文档和图片。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月3日(周五) 晚上11:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zizifn/v2ray-heroku] 部署失败 (Issue #6)




 
fork完并修改了一些配置如下：
  
 
app.json文件
 {   "name": "V2Ray",   "description": "Deploy V2ray on Heroku.",   "keywords": [       "V2Ray"   ],   "env": {       "UUID": {           "description": "V2Ray UUID",           "value": "ce7ea10b-5b27-49ab-a93d-6b184df9cce9"       },       "AID": {           "description": "V2Ray AlterID",           "value": 0       }   },   "website": "https://github.com/zizifn/v2ray-heroku",   "repository": "https://github.com/zizifn/v2ray-heroku",   "stack": "container" }
 

 
startup.sh文件
 "inbounds": [       {           "port": $PORT,           "protocol": "vmess",           "settings": {               "clients": [                   {                       "id": "$UUID",                       "level": 0,                       "alterId": $AID                   }               ],                "decryption": "none"           },           "streamSettings": {               "network": "ws",               "allowInsecure": false,               "wsSettings": {                   "path": "/$UUID-vmess"               }           }       }   ]
 

 
main.yml文件
 更新了版本 ***@***.***
 
 
建立 Environments部署时报的错

**Comment by zizifn** [comment]
你自定义了aid，这个需要改github action的配置文件，然后传入到heroku中，改APP.json是没有用的。建议在原本好用前提下，在增加配置。

**Comment by fangxingweiai** [comment]
直接配置文件中写死了alterid，然后部署还是报那个错，但是不影响使用，多谢！
