### ISSUE TITLE
加上heroku的自动切换功能吧

### ISSUE THREAD

**Issue by honeyshine75** [zizifn/v2ray-heroku#8]
我得想法是这样的：
**原因**
heroku每个账号550h/月，只能用20多天；
**功能描述**
hreoku免费实例自动切换；
**实现**
方法1
_每天凌晨利用action功能自动stop，早上自动start；_
缺点
_不一定哪天凌晨会使用，或者晚上因为不能访问Google而耗电增加；_

方法2
_两个heroku账号，上半个月和下半个月切换。或者白天晚上切换。_
缺点
_实现起来可能比较复杂，如果要客户端无感切用cf的话，需要action操作cf_

**Comment by zizifn** [comment]
第一种方式很好实现，只需要加个 action 触发已有 action 就可以。第二种方式，正如你所说，如果要客户端无感，需要cf。。我比较喜欢第一种，让我做下research。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月12日(周六) 上午9:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zizifn/v2ray-heroku] 加上heroku的自动切换功能吧 (Issue #8)




 
我得想法是这样的：
 原因
 heroku每个账号550h/月，只能用20多天；
 功能描述
 hreoku免费实例自动切换；
 实现
 方法1
 每天凌晨利用action功能自动stop，早上自动start；
 缺点
 不一定哪天凌晨会使用，或者晚上因为不能访问Google而耗电增加；
 
方法2
 两个heroku账号，上半个月和下半个月切换。或者白天晚上切换。
 缺点
 实现起来可能比较复杂，如果要客户端无感切用cf的话，需要action操作cf

**Comment by honeyshine75** [comment]
github的action自带cron应该可以的，需要稍稍改造下，把现在的参数去掉，改成3个分开的action。其中stop和start需要设置cron规则。

**Comment by honeyshine75** [comment]
我简单的实现了一下，说下我的思路：
**1. cf workers改进**
增加语句
`if(new Date().getDate() > 15) {
      url.hostname="xx1.herokuapp.com";
    } else {
      url.hostname="xx2.herokuapp.com";
    }`
**2. 新增库和actions cron**
    库1： 每月1日部署和启动，每月15日停止
    库2： 每月15日部署和启动，每月1日停止

**Comment by zizifn** [comment]
谢谢，正在旅途中。
对于第一种方案，我其实不太喜欢多创建多个action，因为action用的是corn，这会导致以后所有fork项目都会有自动跑的job。。我准备在已有action加一个参数，除非用户手动把这个参数默认值改了，然后check in 到自己repo 下，否则corn job 虽然跑，但是什么都不做。。


对于cf，你的建议可行。先搞定第一种吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月13日(周日) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zizifn/v2ray-heroku] 加上heroku的自动切换功能吧 (Issue #8)




 
我简单的实现了一下，说下我的思路：
 1. cf workers改进
 增加语句
 if(new Date().getDate() &gt; 15) { url.hostname="xx1.herokuapp.com"; } else { url.hostname="xx2.herokuapp.com"; }
 2. 新增库和actions cron
 库1： 每月1日部署和启动，每月15日停止
 库2： 每月15日部署和启动，每月1日停止

**Comment by zhaoguomanong** [comment]
> 我简单的实现了一下，说下我的思路： **1. cf workers改进** 增加语句 `if(new Date().getDate() > 15) { url.hostname="xx1.herokuapp.com"; } else { url.hostname="xx2.herokuapp.com"; }` **2. 新增库和actions cron** 库1： 每月1日部署和启动，每月15日停止 库2： 每月15日部署和启动，每月1日停止

其实根据日期在workers里面进行分流，上半月用domain1,下半个月用domain2 已经够用了。将两个domain对应的容器全部一直开启不用管他，超过半小时没访问自己就睡眠了。 在用domain1的时候没必要手动stop 另外一个。Heroku会自动帮你搞定。

**Comment by zizifn** [comment]
> > 我简单的实现了一下，说下我的思路： **1. cf workers改进** 增加语句 `if(new Date().getDate() > 15) { url.hostname="xx1.herokuapp.com"; } else { url.hostname="xx2.herokuapp.com"; }` **2. 新增库和actions cron** 库1： 每月1日部署和启动，每月15日停止 库2： 每月15日部署和启动，每月1日停止
> 
> 其实根据日期在workers里面进行分流，上半月用domain1,下半个月用domain2 已经够用了。将两个domain对应的容器全部一直开启不用管他，超过半小时没访问自己就睡眠了。 在用domain1的时候没必要手动stop 另外一个。Heroku会自动帮你搞定。

自从我知道，app会自己休眠，我就没有一直想好，怎么做这个功能。另外repo 已经支持，根据不同得github环境配置不同heroku 账户。

**Comment by honeyshine75** [comment]
> > 我简单的实现了一下，说下我的思路： **1. cf workers改进** 增加语句 `if(new Date().getDate() > 15) { url.hostname="xx1.herokuapp.com"; } else { url.hostname="xx2.herokuapp.com"; }` **2. 新增库和actions cron** 库1： 每月1日部署和启动，每月15日停止 库2： 每月15日部署和启动，每月1日停止
> 
> 其实根据日期在workers里面进行分流，上半月用domain1,下半个月用domain2 已经够用了。将两个domain对应的容器全部一直开启不用管他，超过半小时没访问自己就睡眠了。 在用domain1的时候没必要手动stop 另外一个。Heroku会自动帮你搞定。

这个特性有文档吗？如果这样的话只需要定期更新两个heroku就可以了

**Comment by zizifn** [comment]
> > > 我简单的实现了一下，说下我的思路： **1. cf workers改进** 增加语句 `if(new Date().getDate() > 15) { url.hostname="xx1.herokuapp.com"; } else { url.hostname="xx2.herokuapp.com"; }` **2. 新增库和actions cron** 库1： 每月1日部署和启动，每月15日停止 库2： 每月15日部署和启动，每月1日停止
> > 
> > 
> > 其实根据日期在workers里面进行分流，上半月用domain1,下半个月用domain2 已经够用了。将两个domain对应的容器全部一直开启不用管他，超过半小时没访问自己就睡眠了。 在用domain1的时候没必要手动stop 另外一个。Heroku会自动帮你搞定。
> 
> 这个特性有文档吗？如果这样的话只需要定期更新两个heroku就可以了

就在readme的开始部分。
<img width="299" alt="image" src="https://user-images.githubusercontent.com/1803942/162942369-63fee711-a6e0-4729-bbb9-13fc8f196e26.png">

**Comment by zhaoguomanong** [comment]
> > > 我简单的实现了一下，说下我的思路： **1. cf workers改进** 增加语句 `if(new Date().getDate() > 15) { url.hostname="xx1.herokuapp.com"; } else { url.hostname="xx2.herokuapp.com"; }` **2. 新增库和actions cron** 库1： 每月1日部署和启动，每月15日停止 库2： 每月15日部署和启动，每月1日停止
> > 
> > 
> > 其实根据日期在workers里面进行分流，上半月用domain1,下半个月用domain2 已经够用了。将两个domain对应的容器全部一直开启不用管他，超过半小时没访问自己就睡眠了。 在用domain1的时候没必要手动stop 另外一个。Heroku会自动帮你搞定。
> 
> 这个特性有文档吗？如果这样的话只需要定期更新两个heroku就可以了

我说的是app会自己睡眠，这个经过测试确实没访问半小时后自己就自动睡眠了。

**Comment by zizifn** [comment]
> > > > 我简单的实现了一下，说下我的思路： **1. cf workers改进** 增加语句 `if(new Date().getDate() > 15) { url.hostname="xx1.herokuapp.com"; } else { url.hostname="xx2.herokuapp.com"; }` **2. 新增库和actions cron** 库1： 每月1日部署和启动，每月15日停止 库2： 每月15日部署和启动，每月1日停止
> > > 
> > > 
> > > 其实根据日期在workers里面进行分流，上半月用domain1,下半个月用domain2 已经够用了。将两个domain对应的容器全部一直开启不用管他，超过半小时没访问自己就睡眠了。 在用domain1的时候没必要手动stop 另外一个。Heroku会自动帮你搞定。
> > 
> > 
> > 这个特性有文档吗？如果这样的话只需要定期更新两个heroku就可以了
> 
> 我说的是app会自己睡眠，这个经过测试确实没访问半小时后自己就自动睡眠了。

https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping

**Comment by hzdlive** [comment]
cloudflare tunnel 这一步我按教程走，但是Tunnels里status 一直显示inactive

**Comment by zizifn** [comment]
> cloudflare tunnel 这一步我按教程走，但是Tunnels里status 一直显示inactive

麻烦您新开个issue，隐去信息，截个图？

**Comment by hzdlive** [comment]
> 
不好意思，我token复制时，把全部了的都复制进去了。后来仔细检查，只制复制token段就可以了。谢谢

**Comment by conancheng** [comment]
![image](https://user-images.githubusercontent.com/24214834/165225808-218329bf-a84c-4437-8be3-ee3dbff6258b.png)
多账号一直出错。。。换了eu区也不行

**Comment by zizifn** [comment]
> ![image](https://user-images.githubusercontent.com/24214834/165225808-218329bf-a84c-4437-8be3-ee3dbff6258b.png) 多账号一直出错。。。换了eu区也不行
  
看错误，你的 v2rayconan 环境，app 名字 应该和主环境一样了。。。

**Comment by conancheng** [comment]
> 

环境名字和app名字都要跟原来的主环境不一样？

**Comment by zizifn** [comment]
> > 
> 
> 环境名字和app名字都要跟原来的主环境不一样？

环境的意思，是你有多个heroku 账号，或者你想部署多个不同的heroku app。。。当然推荐不应该和主环境一致。。如果一样，就没有必要创建环境了。。你这个错误，大概率是 APP_NAME 和其他人的app名字重复。。APP_NAME必须不能和任何人的有重复。

**Comment by zizifn** [comment]
> > > 
> > 
> > 
> > 环境名字和app名字都要跟原来的主环境不一样？
> 
> 环境的意思，是你有多个heroku 账号，或者你想部署多个不同的heroku app。。。当然推荐不应该和主环境一致。。如果一样，就没有必要创建环境了。。你这个错误，大概率是 APP_NAME 和其他人的app名字重复。。APP_NAME必须不能和任何人的有重复。

另外eu 是支持的，但是你必须先把自己的app 删除掉。。因为heroku 不支持app 直接切换区域。一个app 区域在创建时候就已经确定，后续deploy 改变不了。。

**Comment by conancheng** [comment]
> > > 
> > 
> > 
> > 环境名字和app名字都要跟原来的主环境不一样？
> 
> 环境的意思，是你有多个heroku 账号，或者你想部署多个不同的heroku app。。。当然推荐不应该和主环境一致。。如果一样，就没有必要创建环境了。。你这个错误，大概率是 APP_NAME 和其他人的app名字重复。。APP_NAME必须不能和任何人的有重复。

嗯 改了后成功了。。。

**Comment by conancheng** [comment]
也是见鬼了。。。。部署成功后主的可以连的上 环境里的备用的死活连接不上
![image](https://user-images.githubusercontent.com/24214834/165235021-fbd69931-c27b-4616-b4cc-095a9c900025.png)
cloudflare里面我也单独设置了，出错的GET这个如下：
![image](https://user-images.githubusercontent.com/24214834/165235137-5a528c4d-22af-4ee8-b501-fee2bc402bdd.png)
正常的这个GET如下：
![image](https://user-images.githubusercontent.com/24214834/165235213-b463ffb8-f1be-413e-b473-7cc79b1f141d.png)
